config/routes.rb
SocialGym::Application.routes.draw do

	resources :users do
		resources :measurements
		resources :goals
		member do
		  get :following, :followers
		end
	end
	resources :single_excercises
	resources :routines
	resources :password_resets
	resources :routine_days, only: [:create, :destroy]
	resources :sessions, only: [:new, :create, :destroy]
	resources :relationships, only: [:create, :destroy]
	
	
    match '/signup',  to: 'users#new'
	
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete
	
	
	
	
    root to: 'static_pages#home'
    match '/help', to: "static_pages#help"
  

 

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :admin
  has_secure_password
  
  has_many :routines, dependent: :destroy
  has_many :goals, dependent: :destroy
  has_many :measurements, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  before_save { |user| user.email = email.downcase }
  before_create { generate_token(:remember_token) }
  
   validates :name, presence: true, length: { maximum: 50 }
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
				  uniqueness: { case_sensitive: false }
				  
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true
	
	def self.search(search)
	  if search
		find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
	  else
		find(:all)
	  end
	end
	
	def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
	end

	def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
	end
	def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
	end
	
	def send_password_reset
	  generate_token(:password_reset_token)
	  self.password_reset_sent_at = Time.zone.now
	  save!(validate: false)
	  UserMailer.password_reset(self).deliver
	end
	
	private

    def generate_token(column)
	  begin
		self[column] = SecureRandom.urlsafe_base64
	  end while User.exists?(column => self[column])
    end
	
	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
	before_filter :correct_user,   only: [:edit, :update]
	before_filter :admin_user,     only: [:destroy, :new]

  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  
  def show
	@user = User.find(params[:id])
	if correct_user_without_redirect
		@routines = @user.routines
	else
	    @routines = @user.routines.where(private: false)
	end
	
	@measurements = @user.measurements
	
	@complete_goals = @user.goals.where(complete: true)
	@incomplete_goals = @user.goals.where(complete: false)
  end
  
  def new
	@user = User.new
  end
  
  
  def index
    @users = User.search(params[:search])
  end
  
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Perfil actualizado"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Usuario eliminado."
    redirect_to users_url
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
		UserMailer.registration_confirmation(@user).deliver  
		sign_in @user
		flash[:success] = "Bienvenido a SocialGym!"
		redirect_back_or @user
    else
      render 'new'
    end
  end
  
   private

    
	
	def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
	def correct_user_without_redirect
      @user = User.find(params[:id])
      current_user?(@user)
    end
	def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "eliminar", user, method: :delete,
                                  data: { confirm: "¿Está seguro?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Actualiza tu perfil</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label  :name, "Nombre" %>
      <%= f.text_field :name %>

      <%= f.label :email, "Email" %>
      <%= f.text_field :email %>

      <%= f.label :password, "Contraseña" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmar contraseña" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Guardar cambios", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">cambiar</a>
  </div>
</div>

app/views/users/index.html.erb
<h1>Todos los usuarios</h1>

<%= form_tag users_path, method: 'get' do %>
	<p>
		<%= text_field_tag  :search, params[:search] %>
		<%= submit_tag "Buscar", name: nil %>
	</p>
<% end %>

<ul class="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<h1>Registrar nuevo usuario</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
		 <%= render 'shared/error_messages',  object: f.object %>
      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name %>

      <%= f.label :email, "Email" %>
      <%= f.text_field :email %>

      <%= f.label :password, "Contraseña" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmar contraseña" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Crear cuenta", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class= "span3">
    <section>
      <h1>
        <%= gravatar_for @user, size: 170%>
        
      </h1>
	 </section>
	
	
   <section>
      <%= render 'shared/stats' %>
   </section>
  </aside>
  <section>
  <div class="span9">
	
		<h1><%= @user.name %></h1>
		<%= render 'follow_form' if signed_in? %>
  </div>
  </section>

 
 
</div>

	<p></p>
	<p></p>
	<div class="row">
		<section>
		
		<nav>
		
		
		
		<ul class="nav nav-tabs" id="myTab">
		 
		  <li><a href="#rutinas" data-toggle="tab">Rutinas</a></li>
		  <li><a href="#medidas" data-toggle="tab">Medidas</a></li>
		  <li><a href="#retos" data-toggle="tab">Retos</a></li>
		</ul>
		 
		<div class="tab-content">
		  
		  <div class="tab-pane active" id="rutinas"><% if current_user? @user %>
													<p><%= link_to 'Nueva Rutina', new_routine_path %></p>
     										<% end %>
											<% if @user.routines.any? %>
												<ol class="routines">
												<%= render @routines %> 
												</ol>
											<% else %>
												<p>Este usuario no ha creado ninguna rutina</p>
											<% end %></div>
		  <div class="tab-pane" id="medidas"><%= render "/measurements/index" %></div>
		  <div class="tab-pane" id="retos"><%= render "/goals/index" %></div>
		</div>
		</nav>
		</section>
		 
		<script>
		  $(function () {
			$('#myTab a:first').tab('show');
		  })
		</script>
	</div>

	

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
     
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>