config/routes.rb
SocialGym::Application.routes.draw do

	resources :users do
		resources :measurements
		resources :goals
		member do
		  get :following, :followers
		end
	end
	resources :single_excercises
	resources :routines
	resources :password_resets
	resources :routine_days, only: [:create, :destroy]
	resources :sessions, only: [:new, :create, :destroy]
	resources :relationships, only: [:create, :destroy]
	
	
    match '/signup',  to: 'users#new'
	
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete
	
	
	
	
    root to: 'static_pages#home'
    match '/help', to: "static_pages#help"
  

 

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base

  include PublicActivity::Common
  attr_accessible :back, :height, :leftArm, :leftLeg, :rightArm, :rightLeg, :waits, :weight
 
  belongs_to :user
  
  validates_numericality_of :back, :only_integer =>true, :greater_than_or_equal_to =>0, :message => "invalid fundays"
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  # GET /measurements
  # GET /measurements.json
  before_filter :get_user
  def get_user
	@user = User.find(params[:user_id])
  end
  def index
    @measurements = @user.measurements

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @measurements }
    end
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
    @measurement = @user.measurements.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @measurement }
    end
  end

  # GET /measurements/new
  # GET /measurements/new.json
  def new
    @measurement = current_user.measurements.build
  end

  # GET /measurements/1/edit
  def edit
    @measurement = @user.measurements.find(params[:id])
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = current_user.measurements.build(params[:measurement])
	
	if @measurement.save
		@measurement.create_activity :create, owner: current_user
		respond_to do |format|
			format.html {redirect_to user_measurements_url(@user)}
			format.js
		end
	else
		redirect_to @user
	end
  end

  # PUT /measurements/1
  # PUT /measurements/1.json
  def update
    @measurement = @user.measurements.find(params[:id])

    respond_to do |format|
      if @measurement.update_attributes(params[:measurement])
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement = @user.measurements.find(params[:id])
    @measurement.destroy

    respond_to do |format|
      format.html { redirect_to measurements_url }
	  format.js
    end
  end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/_form.html.erb
<%= form_for([@user, @measurement], remote: true) do |f| %>
  <% if @measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
      <% @measurement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight, "Peso:" %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height, "Altura:" %><br />
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :rightArm, "Brazo derecho:" %><br />
    <%= f.number_field :rightArm %>
  </div>
  <div class="field">
    <%= f.label :leftArm, "Brazo izquierdo:" %><br />
    <%= f.number_field :leftArm %>
  </div>
  <div class="field">
    <%= f.label :back, "Espalda:" %><br />
    <%= f.number_field :back %>
  </div>
  <div class="field">
    <%= f.label :waits, "Cintura:" %><br />
    <%= f.number_field :waits %>
  </div>
  <div class="field">
    <%= f.label :rightLeg, "Pierna derecha:" %><br />
    <%= f.number_field :rightLeg %>
  </div>
  <div class="field">
    <%= f.label :leftLeg, "Pierna Izquierda:" %><br />
    <%= f.number_field :leftLeg %>
  </div>
  <div class="actions">
    <%= f.submit "Crear registro" %>
  </div>
<% end %>

app/views/measurements/_index.html.erb
<h2>Listado de medidas de <%= @user.name %></h2>
	<table class="table table-bordered" id = "meausurementTable" >
	  <tr>
		<th>Fecha</th>
		<th>Peso</th>
		<th>Altura</th>
		<th>Brazo Derecho</th>
		<th>Brazo Izquierdo</th>
		<th>Espalda</th>
		<th>Cintura</th>
		<th>Pierna Derecha</th>
		<th>Pierna Izquierda</th>
		<th></th>
		
		
		
	  </tr>

	<%= render @measurements %>

	</table>
<% if current_user? @user %>
<%= link_to 'Nuevo registro de medidas', new_user_measurement_path(@user),id: "new_link_measurement", remote: true %>
<% end %>

app/views/measurements/_measurement.html.erb
<tr id="edit_measurement_<%= measurement.id %>">
	<td><%= measurement.created_at %>
    <td><%= measurement.weight %> kg</td>
    <td><%= measurement.height %> cm</td>
    <td><%= measurement.rightArm %> cm</td>
    <td><%= measurement.leftArm %> cm</td>
    <td><%= measurement.back %> cm</td>
    <td><%= measurement.waits %> cm</td>
    <td><%= measurement.rightLeg %> cm</td>
    <td><%= measurement.leftLeg %> cm</td>
    <td><%= link_to 'Eliminar', [@user,measurement], method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
 </tr>

app/views/measurements/create.js.erb
$('#new_measurement').remove();
$('#new_link_measurement').show();
$('#meausurementTable').append('<%= j render(@measurement) %>');

app/views/measurements/destroy.js.erb
$('tr#edit_measurement_<%= @measurement.id %>').remove();

app/views/measurements/edit.html.erb
<h1>Editing measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', @measurement %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/new.html.erb
<h1>New measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', user_measurements_path(@user) %>

app/views/measurements/new.js.erb
$('#new_link_measurement').hide().after('<%= j render("form") %>');

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Weight:</b>
  <%= @measurement.weight %>
</p>

<p>
  <b>Height:</b>
  <%= @measurement.height %>
</p>

<p>
  <b>Rightarm:</b>
  <%= @measurement.rightArm %>
</p>

<p>
  <b>Leftarm:</b>
  <%= @measurement.leftArm %>
</p>

<p>
  <b>Back:</b>
  <%= @measurement.back %>
</p>

<p>
  <b>Waits:</b>
  <%= @measurement.waits %>
</p>

<p>
  <b>Rightleg:</b>
  <%= @measurement.rightLeg %>
</p>

<p>
  <b>Leftleg:</b>
  <%= @measurement.leftLeg %>
</p>


<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>