config/routes.rb
SocialGym::Application.routes.draw do

	resources :users do
		resources :measurements
		resources :goals
		member do
		  get :following, :followers
		end
	end
	resources :single_excercises
	resources :routines
	resources :password_resets
	resources :routine_days, only: [:create, :destroy]
	resources :sessions, only: [:new, :create, :destroy]
	resources :relationships, only: [:create, :destroy]
	
	
    match '/signup',  to: 'users#new'
	
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete
	
	
	
	
    root to: 'static_pages#home'
    match '/help', to: "static_pages#help"
  

 

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  include PublicActivity::Common
  attr_accessible :complete, :name, :user_id
  belongs_to :user
  
   validates :name, presence: true, length: { maximum: 100 }
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	before_filter :get_user
	def get_user
		@user = User.find(params[:user_id])
	end
	
	def index
    @complete_goals = @user.goals.where(complete: true)
	@incomplete_goals = @user.goals.where(complete: false)

    respond_to do |format|
      format.html # index.html.erb
      
    end
  end
  def show
    @goal = @user.goals.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @goal }
    end
  end
  def new
    @goal = current_user.goals.build
  end

  # GET /goals/1/edit
  def edit
    @goal = @user.goals.find(params[:id])
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = current_user.goals.build(params[:goal])
	if @goal.save
		@goal.create_activity :create, owner: current_user
		flash[:success] = "Rutina creada!"
		respond_to do |format|
			format.html {redirect_to user_goals_url(@user)}
			format.js
		end
	else
		redirect_to @user
	end
  end

  # PUT /goals/1
  # PUT /goals/1.json
  def update
    @goal = @user.goals.find(params[:id])
	@goal.update_attributes!(params[:goal])
	@goal.create_activity :update, owner: current_user
    respond_to do |format|
		format.html {redirect_to user_goals_url(@user)}
		format.js
	end
    
    
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal = @user.goals.find(params[:id])
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to user_goals_url(@user) }
      format.json { head :no_content }
	  format.js
    end
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for([@user,@goal], remote: true) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Crear reto" %>
<% end %>

app/views/goals/_goal.html.erb
<%= form_for([@user, goal], remote: true) do |f| %>
<% if current_user? @user %>
  <%= f.check_box :complete %>
  <%= f.submit "Actualizar"%>
 <% end %>
  <%= f.label :complete, goal.name, class: "checkbox inline" %>
  <p></p>
  <% if goal.complete %>
  
		<span class="timeAgo"> <%= time_ago_in_words(goal.updated_at) %> ago. </span>
  <% else %>
	<span class="timeAgo"> <%= time_ago_in_words(goal.created_at) %> ago </span>
  <% end %>
  <% if current_user? @user %>
    <%= link_to "(eliminar)", [@user,goal], method: :delete, data: {confirm: "¿Estas seguro?"}, remote: true %>
  <% end%>
<% end %>

app/views/goals/_index.html.erb
<h2>Lista de Retos</h2>

<h3>Retos por completar</h3>
<% if current_user? @user %>
	<%= link_to "Nuevo Reto", new_user_goal_path(@user), id: "new_link", remote: true %>
<%end%>
<div class="goals" id="incomplete_goals">
  <%= render @incomplete_goals %>
</div>

<h3>Retos completados</h3>
<div class="goals" id="complete_goals">
  <%= render @complete_goals %>
</div>

app/views/goals/create.js.erb
$('#new_goal').remove();
$('#new_link').show();
$('#incomplete_goals').append('<%= j render(@goal) %>');
$('#edit_goal_<%= @goal.id %>').submitOnCheck();

app/views/goals/destroy.js.erb
$('#edit_goal_<%= @goal.id %>').remove();

app/views/goals/new.html.erb
<h1>Nuevo reto</h1>

<%= render 'form' %>

<p><%= link_to "Back to tasks", user_goals_path(@user) %></p>

app/views/goals/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/goals/update.js.erb
var formGoal =   $('#edit_goal_<%= @goal.id %>');
<% if @goal.complete? %>
  formGoal.find('.timeAgo').text('<%= time_ago_in_words(@goal.updated_at) %> ago.')
  formGoal.appendTo('#complete_goals');

<% else %>
  formGoal.find('.timeAgo').text('<%= time_ago_in_words(@goal.created_at) %> ago.')
  formGoal.appendTo('#incomplete_goals');
 
<% end %>